### ISSUE TITLE
Thread profiling screen, selected thread color similar to other color

### ISSUE THREAD

**Issue by thewizkid87** [krud-dev/boost#293]

**Comment by Idane** [comment]
`TIMED_WAITING`, when pressed, has a very similar color to `WAITING`
<img width="467" alt="image" src="https://user-images.githubusercontent.com/3495615/230767846-f8cd2b39-9841-4c1a-97a6-dba8d25e7a86.png">
Even less distinguishable when contrasted by unpressed `TIMED_WAITING` (Above is `WAITING`, below is pressed `TIMED_WAITING`
<img width="239" alt="image" src="https://user-images.githubusercontent.com/3495615/230767862-fb2005c7-6362-487d-9c5f-4d7afaa398bd.png">
