### ISSUE TITLE
Changing our name

### ISSUE THREAD

**Issue by Idane** [krud-dev/boost#365]
We received some feedback that the Boost name conflicts with a [well known set of C++ libraries](https://www.boost.org/), an issue [that we could not have possibly forseen](https://lmgtfy.app/?q=boost+github) before releasing. 

So, let's try to decide on a path going forward, possible options:

👍 Leave Boost 
❤ Ostara - "West Germanic spring goddess"
😄 Ajari - Punjabi word for Shepherd
🎉 Sprynter - Derived from Sprinter
🚀 Tefiti - Goddess from Moana
👀 Other suggestions

**Comment by tobidope** [comment]
Lenz old Germanic for spring 🤷‍♂️

**Comment by Idane** [comment]
Ostara it is!
