### ISSUE TITLE
URL Regex does not permit dashes in domain, even though domains may contain dashes

### ISSUE THREAD

**Issue by Chris-Schuster-Daydream** [krud-dev/boost#371]
## Prerequisites

- ~~[ ] Using npm~~
- ~~[ ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)~~
- ~~[ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)~~
- ~~[ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)~~
- ~~[ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`~~
- [*] Using App Image release executable

## Expected Behavior

An instance with an URL containing a dash in the domain should not trigger the "Invalid URL" error status.

## Current Behavior
The "Invalid URL" warning message is shown:
![Screenshot from 2023-04-21 16-09-01](https://user-images.githubusercontent.com/93141240/233735233-c7269f89-f4e1-4ac0-a252-5bd709d3f135.png)

In https://github.com/krud-dev/boost/blob/789d2e0f21f91c46bff20e3da9bfcd76e772dff2/src/renderer/constants/regex.ts#L2 The `\w` metacharacter matches underscores (`_`) but domains use dashes (`-`)

## Steps to Reproduce
1. Start Boost
2. Click 'Add Instance' button
3. Type `https://example-oops.com/actuator` into the Actuator URL input
4. See `Invalid URL` appear beneath

## Possible Solution (Not obligatory)
Regex solution: `/^https?:\/\/[-a-zA-Z0-9]+(\.[-a-zA-Z0-9]+)*(:[0-9]+)?\/?(\/[.-a-zA-Z0-9]*)*$/`

Full solution involves implementing https://datatracker.ietf.org/doc/html/rfc3986#section-3.2

## Context
This issue blocks using the app for all environments before our Production instance (we have one each of a Development, Quality Assurance, Staging, and Production environments).

## Your Environment
Using `Boost-0.4.3.AppImage` from https://github.com/krud-dev/boost/releases/tag/v0.4.3 on Ubuntu 22.04

**Comment by Idane** [comment]
Seems to have been solved in #369 and #370, so you should be able to use it as soon as the next release is out, just checking a few corners before I actually release so I'll leave this open for now

**Comment by Idane** [comment]
@Chris-Schuster-Daydream 

Released 0.5.0 and I can't reproduce it there. It should update automatically for you, can you give it another shot?
